site_name: Wiskundewijs
site_author: Marc Serrano Altena
site_url: https://wiskundewijs.com/
site_description: Hier worden verschillende wiskundige onderwerpen duidelijk en helder behandelt. De hoofdstukken hebben een theorie sectie waar de stof wordt uitgelegt en daarna worden wat voorbeelden behandelt om te laten zien hoe de theorie toegepast wordt in de opdrachten. 
copyright: Copyright &copy; 2025, Marc Serrano Altena <br> <a href="#__consent" style="color:#B0B0B0"><i>Cookie instellingen</i></a>


docs_dir: 'mkdocs'
site_dir: 'docs\static\mkdocs_build'


theme:
  name: "material"
  palette: 
    scheme: 
      slate

    primary: 
      teal

  language: nl
  logo: assets/images/general/calculator-variant-outline.svg
  favicon: assets/images/general/calculator-variant.ico

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - search.suggest

  custom_dir: mkdocs\overrides

  static_template: 404.html


extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/marc-serrano-altena-a96800285/

    - icon: fontawesome/brands/github
      link: https://github.com/M-Serrano-Altena

    - icon: material/email-outline
      link: mailto:<marcsa@wiskundewijs.com>

  generator: false

  analytics:
    provider: google
    property: G-4JQXCEL3Q5

  consent:
    title: Cookies
    description: Deze website maakt gebruik van cookies om te zien hoe de website gebruikt wordt. Zo kunnen we jouw ervaring nog beter maken! 
    actions:
      - accept
      # - reject
      - manage
      

    feedback:
      title: Begrijp je de stof nu beter?
      ratings:
        - icon: material/thumb-up-outline
          name: Ik begrijp de stof nu beter
          data: 1
          note: Bedankt voor de feedback! Om ervoor te zorgen dat wiskundewijs nóg beter wordt, zou ik <a href="https://docs.google.com/forms/d/e/1FAIpQLSdUuPlxDYomx3nLl63BQcFR0jCbQMaQIpFh37J53_UaVJELeA/viewform?usp=pp_url&entry.1328585866={title}" target="_blank" rel="noopener">jouw feedback</a> heel erg waarderen! 
        - icon: material/thumb-down-outline
          name: De stof is nog een beetje onduidelijk
          data: 0
          note: Bedankt voor de feedback! Ik zou het heel erg waarderen als je mij vertelt wat jij denkt dat verbeterd kan worden. <a href="https://docs.google.com/forms/d/e/1FAIpQLSebi8Nv-t1BBU7mzvMK8COd_1aHSTnjgzBQWQXhjt64OuVsFQ/viewform?usp=pp_url&entry.1328585866={title}" target="_blank" rel="noopener">Jouw feedback</a> kan mensen helpen die tegen hetzelfde aanlopen!

  static_templates:
    - 404.html
    - main_sections/primitieve/introductie_primitieven.md

nav:
  - Home: index.md
  
  - Stof:
    - basisvaardigheden.md
    - percentages.md
    - statistiek.md
    - De Stelling van Pythagoras: pythagoras.md
    - Kwadratische Vergelijkingen: kwadratische_vergelijkingen.md
    - ongelijkheden.md
    - Stelsels van Vergelijkingen: stelsels_van_vergelijkingen.md
    - De Afgeleide Functie: afgeleide.md
    - De Primitieve Functie: primitieve.md
    
    - goniometrie.md

  - Oplosser: oplosser.md

  - bijles.md
  

not_in_nav: |
  meetkunde.md
  primitieve_single_page.md
  main_sections/primitieve/introductie_primitieven.md
  main_sections/primitieve/introductie_integralen.md
  main_sections/primitieve/oppervlakte_tussen_grafieken.md
  main_sections/primitieve/oppervlakte_wentelen_x.md
  main_sections/primitieve/omwentelings_tussen_grafieken.md
  main_sections/primitieve/oppervlakte_wentelen_y.md
  
plugins:
  - search


markdown_extensions:
  - def_list

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true

  - attr_list
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra_javascript:
  - https://cdn.jsdelivr.net/npm/marked/marked.min.js 
  - javascripts/load_sections.js
  - javascripts/mathjax.js

extra_css:
  - stylesheets/extra.css