site_name: Wiskunde uitleg

theme:
  name: "material"
  logo: assets/math_normal.svg
  favicon: assets/math_bold.svg

nav:
  - Home Pagina: index.md
  - Stelling van Pythagoras: pythagoras.md
  - De Afgeleide Functie: derivative.md
  - De Eenheidscirkel: unit_circle.md


plugins:
  - mkdocstrings


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js