site_name: Wiskundewijs
site_author: Marc Serrano Altena
site_url: https://wiskundewijs.com/
site_description: Hier worden verschillende wiskundige onderwerpen duidelijk en helder behandelt. De hoofdstukken hebben een theorie sectie waar de stof wordt uitgelegt en daarna worden wat voorbeelden behandelt om te laten zien hoe de theorie toegepast wordt in de opdrachten. 
copyright: Copyright &copy; 2024, Marc Serrano Altena


theme:
  name: "material"
  palette: 
    scheme: 
      slate

    primary: 
      teal

  language: nl
  logo: assets/images/calculator-variant-outline.svg
  favicon: assets/images/calculator-variant.svg

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/marc-serrano-altena-a96800285/

    - icon: fontawesome/brands/github
      link: https://github.com/M-Serrano-Altena

    - icon: material/email-outline
      link: mailto:<Marc.Serrano.Altena@gmail.com>

  generator: false

  analytics:
    provider: google
    property: G-4JQXCEL3Q5

    feedback:
      title: Begrijp je de stof nu beter?
      ratings:
        - icon: material/thumb-up-outline
          name: Ik begrijp de stof nu beter
          data: 1
          note: Bedankt voor de feedback! Om ervoor te zorgen dat wiskundewijs nóg beter wordt, zou ik <a href="https://docs.google.com/forms/d/e/1FAIpQLSdUuPlxDYomx3nLl63BQcFR0jCbQMaQIpFh37J53_UaVJELeA/viewform?usp=pp_url&entry.1328585866={title}" target="_blank" rel="noopener">jouw feedback</a> heel erg waarderen! 
        - icon: material/thumb-down-outline
          name: De stof is nog een beetje onduidelijk
          data: 0
          note: Bedankt voor de feedback! Ik zou het heel erg waarderen als je mij vertelt wat jij denkt dat verbeterd kan worden. <a href="https://docs.google.com/forms/d/e/1FAIpQLSebi8Nv-t1BBU7mzvMK8COd_1aHSTnjgzBQWQXhjt64OuVsFQ/viewform?usp=pp_url&entry.1328585866={title}" target="_blank" rel="noopener">Jouw feedback</a> kan mensen helpen die tegen hetzelfde aanlopen!

nav:
  - Home: index.md
  
  - Stof:
    - basisvaardigheden.md
    - De Stelling van Pythagoras: pythagoras.md
    - Kwadratische Vergelijkingen: kwadratische_vergelijkingen.md
    - ongelijkheden.md
    - De Afgeleide Functie: afgeleide.md
    - goniometrie.md

  - contact.md

# not_in_nav:
#   contact.md
  
plugins:
  - search


markdown_extensions:
  - def_list

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true

  - attr_list
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/contactInfo.js

extra_css:
  - stylesheets/extra.css