site_name: Wiskunde uitleg

theme:
  name: "material"
  palette: 
    scheme: 
      slate

    primary: 
      teal

  language: nl
  logo: assets/calculator-variant-outline.svg
  favicon: assets/calculator-variant.svg

nav:
  - Stelling van Pythagoras: pythagoras.md
  - De Afgeleide Functie: derivative.md
  - De Eenheidscirkel: unit_circle.md


plugins:
  - mkdocstrings


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js