site_name: Wiskundewijs
site_author: Marc Serrano Altena
site_url: https://m-serrano-altena.github.io/Wiskundewijs/
site_description: Hier worden verschillende wiskundige onderwerpen duidelijk en helder behandelt. De hoofdstukken hebben een theorie sectie waar de stof wordt uitgelegt en daarna worden wat voorbeelden behandelt om te laten zien hoe de theorie toegepast wordt in de opdrachten. 
copyright: Copyright &copy; 2024, Marc Serrano Altena


theme:
  name: "material"
  palette: 
    scheme: 
      slate

    primary: 
      teal

  language: nl
  logo: assets/calculator-variant-outline.svg
  favicon: assets/calculator-variant.svg

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/marc-serrano-altena-a96800285/

    - icon: fontawesome/brands/github
      link: https://github.com/M-Serrano-Altena

    - icon: material/email-outline
      link: mailto:<Marc.Serrano.Altena@gmail.com>

  generator: false


nav:
  - Home: index.md
  
  - Stof:
    - basisvaardigheden.md
    - De Stelling van Pythagoras: pythagoras.md
    - Kwadratische Vergelijkingen: kwadratische_vergelijkingen.md
    - De Afgeleide Functie: derivative.md
    - goniometrie.md

  - contact.md


# not_in_nav:
#   contact.md
  
  
  


plugins:
  - mkdocstrings
  - search


markdown_extensions:
  - def_list

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true

  - attr_list
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences






extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css